apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable-workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
        default: ./config
        description: Path to config files for app
    secrets:
      access-token:
        required: true
        description: The token to use for deploying
    outputs:
      deploy-result:
        value: ${{ jobs.deploy-shared.outputs.result }}
        description: simple value output